name: actors_pedia
description: Actors Encyclopedia App

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #UI
  cupertino_icons: ^1.0.5
  flutter_svg: ^1.1.0
  cached_network_image: ^3.2.1
  google_fonts: ^3.0.1

  #State Management
  flutter_bloc: ^8.0.1

  #Service Locator
  get_it: ^7.2.0

  #Services
  equatable: ^2.0.3
  dartz: ^0.10.1

  #Remote Data
  connectivity_plus: ^2.3.5
  dio: ^4.0.6

  #Local Data
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: any

  # pub run dependency_validator
  dependency_validator: any

flutter:
  uses-material-design: true

  assets:
    - assets/